### ISSUE TITLE
Search bar is white (when signed in).

### ISSUE THREAD

**Issue by Liz-chan** [hyperfekt/google-dark#10]
Please make sure all of the following is true so your issue can be quickly resolved (check like [X]):  
- [x] My version of the userstyle is up to date  
- [x] My version of Stylus is up to date  
- [x] I have searched the existing issues (both open *and closed*) to see if my problem is already reported.
- [x] I have added what browser I use and its version.
- [x] I have given a detailed description of the problem and the steps to reach it.  
- [x] I have added an example URL where the problem occurs.  
- [ ] If I have customized any of the options, I have pinned down with which of them it occurs and provided the changed values here.
- [x] I have saved the page the problem occurs on and attached it here (usually available in the browser context menu - make sure to log out beforehand to preserve your privacy!).
- [x] I have made a screenshot that demonstrates the problem and attached it here.

Userstyle: Search
Stylus version: 1.4.5
Userstyle version: 0.6.19
Browser version: 67.0.3396.87
Steps to reach the problem:
1. Go to Google.com and make sure you're signed in.
2. See ugly white search bar.
3. (It also stays white on the results page when you search for stuff).
4. (Also it only happens when you're signed in).

Expected Behavior: The bar should be dark.
Observed Behavior: It's white and ugly
URL: https://www.google.com/
Customized values that cause the problem: 
Saved page: 
[Issue.zip](https://github.com/hyperfekt/google-dark/files/2129440/Issue.zip)
Screenshot: 
![image](https://user-images.githubusercontent.com/18467466/41803166-436ecf9c-7654-11e8-82bc-42a9f2e5329e.png)
![image](https://user-images.githubusercontent.com/18467466/41803173-4bfeaf38-7654-11e8-8024-3f21c959911b.png)

**Comment by Liz-chan** [comment]
Sweet, thanks.

**Comment by hyperfekt** [comment]
Looks like you're part of some A/B tests, this hasn't rolled out to me yet. ^^
Sorry for the delay, had some trouble with my machine. :<

**Comment by Liz-chan** [comment]
Oh it's fine, I'm just happy it's dark now, woo.
