### ISSUE TITLE
Publish on userstyles.org

### ISSUE THREAD

**Issue by qazip** [hyperfekt/google-dark#14]
Why is this theme not published on userstyles? I find it a bit dangerous to install something via an obfuscated link, as you suggest to do.

**Comment by hyperfekt** [comment]
It is not published on userstyles.org to save myself from myriads of people complaining that it won't work because it requires the Stylish extension.
The link leads back to Github, as you will be able to verify; i just like to have a very rough idea of how many people are actually installing it.
