### ISSUE TITLE
Can't install CSS Stylus

### ISSUE THREAD

**Issue by matheusfaustino** [hyperfekt/google-dark#5]
Hello, first of all, thank you very much for your repo. It's very good.

I'm trying to install the script in another pc and I'm getting this error:
* Windows 10
* Firefox 61.0b9 (64-bit)
* Stylus 1.4.5

```
Stylus failed to parse usercss: stylus:1132:4 1128| color: main-text; 1129| } 1130| .cFitPd 1131| 1132| /* missing terms */ ------------^ 1133| .TXwUJf { 1134| color: main-text-off; 1135| } Error.captureStackTrace is not a function 
```

Yesterday it worked perfectly on my linux machine. 

Thanks ^^

**Comment by hyperfekt** [comment]
Lesson: No change is sufficiently trivial as to not deserve testing.
A small mistake slipped in where I abandoned a selector that I noticed was already included, but did not delete it.

Thanks for both the report and the compliment. :)

**Comment by matheusfaustino** [comment]
You are welcome, thank you for creating this. 

Have a good day.
