### ISSUE TITLE
Featured Snippet isn't themed

### ISSUE THREAD

**Issue by Liz-chan** [hyperfekt/google-dark#6]
Please make sure all of the following is true so your issue can be quickly resolved (check like [X]):  
- [x] My version of the userstyle is up to date  
- [x] My version of Stylus is up to date  
- [x] I have added what browser I use and its version.
- [x] I have searched the existing issues (both open *and closed*) to see if my problem is already reported.
- [x] I have given a detailed description of the problem and the steps to reach it.  
- [x] I have added an example URL where the problem occurs.  
- [ ] If I have customized any of the options, I have pinned down with which of them it occurs and provided the changed values here.
- [x] I have saved the page the problem occurs on and attached it here (usually available in the browser context menu).
- [x] I have made a screenshot that demonstrates the problem and attached it here.

Userstyle: Search
Stylus version: 1.4.5
Userstyle version: 0.5.17
Browser version: Chrome 67
Steps to reach the problem:
1. Search "is car insurance mandatory in us"
2. See problem

Expected Behavior: Featured snippet is dark
Observed Behavior: It's white T-T
URL: http://bit.ly/2LbvbEv
Screenshot: 
![image](https://user-images.githubusercontent.com/18467466/40805584-bf333326-64ec-11e8-8717-c2592d8cce1a.png)

[is car insurance mandatory in us - Google Search.zip](https://github.com/hyperfekt/google-dark/files/2059898/is.car.insurance.mandatory.in.us.-.Google.Search.zip)

**Comment by hyperfekt** [comment]
This is the best I can do for now, since I'm not getting any access to the snippet (even from the US) apart from the saved version you provided - any interaction that the buttons might have I can't style.

**Comment by Liz-chan** [comment]
That's fine, it looks so much better now, thank you!
![image](https://user-images.githubusercontent.com/18467466/40811159-31b081e0-64fe-11e8-8082-f0eccb35eb1a.png)

**Comment by hyperfekt** [comment]
Thank you for the comprehensive report, feel free to add any other issues you might see. :)
