### ISSUE TITLE
Hotels link is grey, not the regular hyperlink colour

### ISSUE THREAD

**Issue by Alfie94** [hyperfekt/google-dark#7]
Userstyle: Search
Stylus version: 1.4.5
Userstyle version: commit 959f520
Browser version: 67.0.3396.62
Steps to reach the problem:
1. Search a town that returns hotels in its widget (eg "Wokingham")

Expected Behavior: Hotels link is a blue link colour
Observed Behavior: Hotels is an almost illegible grey
URL: https://www.google.co.uk/search?q=wokingham
Customized values that cause the problem: Have not customised anything in the userstyle or Google search settings
[wokingham - Google Search_files.zip](https://github.com/hyperfekt/google-dark/files/2063036/wokingham.-.Google.Search_files.zip)
![chrome_2018-06-01_15-28-16](https://user-images.githubusercontent.com/6684330/40846180-bff633e8-65b0-11e8-818a-6be7f865bc60.png)

**Comment by hyperfekt** [comment]
Thanks for the report! :D
It turned despite being a link it's actually supposed to be the normal text color. :thinking:
