### ISSUE TITLE
WOT extension displays icon in new line instead of behind title

### ISSUE THREAD

**Issue by hyperfekt** [hyperfekt/google-dark#9]
@MTRougeau wrote:

> Hey @hyperfekt 
> I have this issue using the WOT extension in Chrome. The extension icon is pushed down to a new line, spacing everything out. This does not happen using other Google Dark theme styles.
> Screenshot:
> ![image](https://user-images.githubusercontent.com/15477491/41431951-293f677e-6fda-11e8-8f7e-b0868493f705.png)
> 
> Using a different dark style:
> ![image](https://user-images.githubusercontent.com/15477491/41431998-5387d61a-6fda-11e8-9ab7-9860f1c13713.png)
>

**Comment by hyperfekt** [comment]
The icons should now be placed perfectly. Interestingly, without this userstyle it is not displayed at all when the title is too long - the difference in how titles are aligned in this userstyle fixes that bug.

**Comment by MTRougeau** [comment]
@hyperfekt Works great! Thanks!
